version: '3.8'
services:
  savey_api:
    platform: linux/amd64
    command: bash -lc "uv run uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
    build: .
    container_name: savey_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 4g